"""add trailer_url to movie

Revision ID: c0058f484076
Revises: ee2a4e712849
Create Date: 2024-07-18 21:50:18.470439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0058f484076'
down_revision = 'ee2a4e712849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('trailer_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'trailer_url')
    # ### end Alembic commands ###
